# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ContactDeveloperDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(589, 563)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pictures/txt_downloader_ico.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-image: url(:/background/pictures/功夫.jpg);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 80, 391, 71))
        self.label.setStyleSheet("font: 20pt \"Muyao-Softbrush\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 200, 441, 71))
        self.label_2.setStyleSheet("font: 20pt \"Muyao-Softbrush\";")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 370, 321, 81))
        self.label_4.setStyleSheet("font: 16pt \"Muyao-Softbrush\";")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.exec_()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "联系开发者"))
        self.label.setText(_translate("Dialog", "e-mail : \n"
                                                "3480339804@qq.com"))
        self.label_2.setText(_translate("Dialog", "Github : \n"
                                                  "https://kgithub.com/wutljs"))
        self.label_4.setText(_translate("Dialog", "请注意：\n"
                                                  "拒绝恶意邮件从你我做起！"))
