# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QMessageBox, QWidget
from set_save_address import Ui_SetSaveAddressDialog
from contact_developer import Ui_ContactDeveloperDialog
from download_novel import Ui_DownloadNovelDialog

import main_picture_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(919, 646)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pictures/txt_downloader_ico.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-image: url(:/background/pictures/MainWindow_background.jpg);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-110, 0, 371, 61))
        self.label.setStyleSheet("font: 20pt \"Muyao-Softbrush\";")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(210, 80, 411, 81))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("font: 20pt \"Muyao-Softbrush\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.setSaveAddressDialog)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(590, 470, 201, 61))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("font: 20pt \"Muyao-Softbrush\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.contactDeveloper)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 220, 411, 81))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("font: 20pt \"Muyao-Softbrush\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.downloadNovel)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 80, 93, 221))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("font: 20pt \"Muyao-Softbrush\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.userInformation)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 919, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pbar小说下载器"))
        self.label.setText(_translate("MainWindow", "          Pbar小说下载器"))
        self.pushButton.setText(_translate("MainWindow", "设置小说存储地址"))
        self.pushButton_4.setText(_translate("MainWindow", "联系开发者"))
        self.pushButton_2.setText(_translate("MainWindow", "下载小说"))
        self.pushButton_3.setText(_translate("MainWindow", "用户\n"
                                                           "须知"))
        self.menu.setTitle(_translate("MainWindow", "久物之味，久则可厌；读书之味，愈久愈深"))

    def setSaveAddressDialog(self):
        Ui_SetSaveAddressDialog().setupUi(Dialog=QDialog())

    def contactDeveloper(self):
        Ui_ContactDeveloperDialog().setupUi(Dialog=QDialog())

    def userInformation(self):
        fp = open('disclaimers.txt', 'r').read()
        QMessageBox.warning(QDialog(), "免责声明", fp, QMessageBox.Yes, QMessageBox.Yes)

    def downloadNovel(self):
        Ui_DownloadNovelDialog().setupUi(Dialog=QDialog())

